### ISSUE TITLE
Implement hook_chain support?

### ISSUE THREAD

**Issue by txr13** [bennettp123/letsencrypt.sh-email-notify-hook#2]
Would be awesome if hook_chain support could be implemented. (See https://github.com/lukas2511/letsencrypt.sh/blob/master/docs/hook_chain.md)

From the look of the documentation and this script itself, I believe that a example renewal of three certificates would result in three separate calls to the hook script. The hook would then wait for one DNS name to be created before completing and moving on to the next iteration, which then has to wait, etc. etc.

Ideally, if hook_chain was implemented, we could either get all the challenges emailed out in a batch (three emails, one for each challenge), or possibly even list all the challenges in a single email. Then the script just has to ensure that all the challenges go live before returning.

**Comment by bennettp123** [comment]
You are correct, the script only supports a single record at a time, and waits after each one, which causes unnecessary delays for certificates with multiple SANs. Using HOOK_CHAIN="yes" could indeed improve this.

It won't improve multiple certificates, but it will improve a single certificate with multiple SANs.

**Comment by bennettp123** [comment]
Fixed in #3 and again in #4
